import Config

read_secret = fn path ->
  case File.read(path) do
    {:ok, contents} -> String.trim(contents)
    _ -> nil
  end
end

db_user = System.get_env("POSTGRES_USER") || "postgres"
db_password_file = System.get_env("POSTGRES_PASSWORD_FILE")

db_password =
  System.get_env("POSTGRES_PASSWORD") ||
    if(db_password_file, do: read_secret.(db_password_file), else: nil) ||
    "postgres"

db_host = System.get_env("POSTGRES_HOST") || "localhost"
db_name = System.get_env("POSTGRES_DB") || "luca_webapp_dev"
db_port = System.get_env("POSTGRES_PORT") || "5432"

# Configure your database
config :luca_webapp, LucaWebapp.Repo,
  username: db_user,
  password: db_password,
  hostname: db_host,
  database: db_name,
  port: String.to_integer(db_port),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :luca_webapp, LucaWebappWeb.Endpoint,
  # Bind to all interfaces when running in Docker.
  http: [
    ip:
      case System.get_env("PHX_SERVER_IP") do
        "0.0.0.0" -> {0, 0, 0, 0}
        _ -> {127, 0, 0, 1}
      end
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Nn64CWw0RI8yEGfigEckVA6TF/2Th8PnQnEzJahAJ8SI/8LvnVltAssnaNO35MGq",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:luca_webapp, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:luca_webapp, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :luca_webapp, LucaWebappWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/luca_webapp_web/router\.ex$",
      ~r"lib/luca_webapp_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :luca_webapp, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
